require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EquipmentalsController do

  # This should return the minimal set of attributes required to create a valid
  # Equipmental. As you add validations to Equipmental, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EquipmentalsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all equipmentals as @equipmentals" do
      equipmental = Equipmental.create! valid_attributes
      get :index, {}, valid_session
      assigns(:equipmentals).should eq([equipmental])
    end
  end

  describe "GET show" do
    it "assigns the requested equipmental as @equipmental" do
      equipmental = Equipmental.create! valid_attributes
      get :show, {:id => equipmental.to_param}, valid_session
      assigns(:equipmental).should eq(equipmental)
    end
  end

  describe "GET new" do
    it "assigns a new equipmental as @equipmental" do
      get :new, {}, valid_session
      assigns(:equipmental).should be_a_new(Equipmental)
    end
  end

  describe "GET edit" do
    it "assigns the requested equipmental as @equipmental" do
      equipmental = Equipmental.create! valid_attributes
      get :edit, {:id => equipmental.to_param}, valid_session
      assigns(:equipmental).should eq(equipmental)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Equipmental" do
        expect {
          post :create, {:equipmental => valid_attributes}, valid_session
        }.to change(Equipmental, :count).by(1)
      end

      it "assigns a newly created equipmental as @equipmental" do
        post :create, {:equipmental => valid_attributes}, valid_session
        assigns(:equipmental).should be_a(Equipmental)
        assigns(:equipmental).should be_persisted
      end

      it "redirects to the created equipmental" do
        post :create, {:equipmental => valid_attributes}, valid_session
        response.should redirect_to(Equipmental.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved equipmental as @equipmental" do
        # Trigger the behavior that occurs when invalid params are submitted
        Equipmental.any_instance.stub(:save).and_return(false)
        post :create, {:equipmental => { "name" => "invalid value" }}, valid_session
        assigns(:equipmental).should be_a_new(Equipmental)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Equipmental.any_instance.stub(:save).and_return(false)
        post :create, {:equipmental => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested equipmental" do
        equipmental = Equipmental.create! valid_attributes
        # Assuming there are no other equipmentals in the database, this
        # specifies that the Equipmental created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Equipmental.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => equipmental.to_param, :equipmental => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested equipmental as @equipmental" do
        equipmental = Equipmental.create! valid_attributes
        put :update, {:id => equipmental.to_param, :equipmental => valid_attributes}, valid_session
        assigns(:equipmental).should eq(equipmental)
      end

      it "redirects to the equipmental" do
        equipmental = Equipmental.create! valid_attributes
        put :update, {:id => equipmental.to_param, :equipmental => valid_attributes}, valid_session
        response.should redirect_to(equipmental)
      end
    end

    describe "with invalid params" do
      it "assigns the equipmental as @equipmental" do
        equipmental = Equipmental.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Equipmental.any_instance.stub(:save).and_return(false)
        put :update, {:id => equipmental.to_param, :equipmental => { "name" => "invalid value" }}, valid_session
        assigns(:equipmental).should eq(equipmental)
      end

      it "re-renders the 'edit' template" do
        equipmental = Equipmental.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Equipmental.any_instance.stub(:save).and_return(false)
        put :update, {:id => equipmental.to_param, :equipmental => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested equipmental" do
      equipmental = Equipmental.create! valid_attributes
      expect {
        delete :destroy, {:id => equipmental.to_param}, valid_session
      }.to change(Equipmental, :count).by(-1)
    end

    it "redirects to the equipmentals list" do
      equipmental = Equipmental.create! valid_attributes
      delete :destroy, {:id => equipmental.to_param}, valid_session
      response.should redirect_to(equipmentals_url)
    end
  end

end
