require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe IncidentalsController do

  # This should return the minimal set of attributes required to create a valid
  # Incidental. As you add validations to Incidental, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "description" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # IncidentalsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all incidentals as @incidentals" do
      incidental = Incidental.create! valid_attributes
      get :index, {}, valid_session
      assigns(:incidentals).should eq([incidental])
    end
  end

  describe "GET show" do
    it "assigns the requested incidental as @incidental" do
      incidental = Incidental.create! valid_attributes
      get :show, {:id => incidental.to_param}, valid_session
      assigns(:incidental).should eq(incidental)
    end
  end

  describe "GET new" do
    it "assigns a new incidental as @incidental" do
      get :new, {}, valid_session
      assigns(:incidental).should be_a_new(Incidental)
    end
  end

  describe "GET edit" do
    it "assigns the requested incidental as @incidental" do
      incidental = Incidental.create! valid_attributes
      get :edit, {:id => incidental.to_param}, valid_session
      assigns(:incidental).should eq(incidental)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Incidental" do
        expect {
          post :create, {:incidental => valid_attributes}, valid_session
        }.to change(Incidental, :count).by(1)
      end

      it "assigns a newly created incidental as @incidental" do
        post :create, {:incidental => valid_attributes}, valid_session
        assigns(:incidental).should be_a(Incidental)
        assigns(:incidental).should be_persisted
      end

      it "redirects to the created incidental" do
        post :create, {:incidental => valid_attributes}, valid_session
        response.should redirect_to(Incidental.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved incidental as @incidental" do
        # Trigger the behavior that occurs when invalid params are submitted
        Incidental.any_instance.stub(:save).and_return(false)
        post :create, {:incidental => { "description" => "invalid value" }}, valid_session
        assigns(:incidental).should be_a_new(Incidental)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Incidental.any_instance.stub(:save).and_return(false)
        post :create, {:incidental => { "description" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested incidental" do
        incidental = Incidental.create! valid_attributes
        # Assuming there are no other incidentals in the database, this
        # specifies that the Incidental created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Incidental.any_instance.should_receive(:update).with({ "description" => "MyString" })
        put :update, {:id => incidental.to_param, :incidental => { "description" => "MyString" }}, valid_session
      end

      it "assigns the requested incidental as @incidental" do
        incidental = Incidental.create! valid_attributes
        put :update, {:id => incidental.to_param, :incidental => valid_attributes}, valid_session
        assigns(:incidental).should eq(incidental)
      end

      it "redirects to the incidental" do
        incidental = Incidental.create! valid_attributes
        put :update, {:id => incidental.to_param, :incidental => valid_attributes}, valid_session
        response.should redirect_to(incidental)
      end
    end

    describe "with invalid params" do
      it "assigns the incidental as @incidental" do
        incidental = Incidental.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Incidental.any_instance.stub(:save).and_return(false)
        put :update, {:id => incidental.to_param, :incidental => { "description" => "invalid value" }}, valid_session
        assigns(:incidental).should eq(incidental)
      end

      it "re-renders the 'edit' template" do
        incidental = Incidental.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Incidental.any_instance.stub(:save).and_return(false)
        put :update, {:id => incidental.to_param, :incidental => { "description" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested incidental" do
      incidental = Incidental.create! valid_attributes
      expect {
        delete :destroy, {:id => incidental.to_param}, valid_session
      }.to change(Incidental, :count).by(-1)
    end

    it "redirects to the incidentals list" do
      incidental = Incidental.create! valid_attributes
      delete :destroy, {:id => incidental.to_param}, valid_session
      response.should redirect_to(incidentals_url)
    end
  end

end
