require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LaborCartsController do

  # This should return the minimal set of attributes required to create a valid
  # LaborCart. As you add validations to LaborCart, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LaborCartsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all labor_carts as @labor_carts" do
      labor_cart = LaborCart.create! valid_attributes
      get :index, {}, valid_session
      assigns(:labor_carts).should eq([labor_cart])
    end
  end

  describe "GET show" do
    it "assigns the requested labor_cart as @labor_cart" do
      labor_cart = LaborCart.create! valid_attributes
      get :show, {:id => labor_cart.to_param}, valid_session
      assigns(:labor_cart).should eq(labor_cart)
    end
  end

  describe "GET new" do
    it "assigns a new labor_cart as @labor_cart" do
      get :new, {}, valid_session
      assigns(:labor_cart).should be_a_new(LaborCart)
    end
  end

  describe "GET edit" do
    it "assigns the requested labor_cart as @labor_cart" do
      labor_cart = LaborCart.create! valid_attributes
      get :edit, {:id => labor_cart.to_param}, valid_session
      assigns(:labor_cart).should eq(labor_cart)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new LaborCart" do
        expect {
          post :create, {:labor_cart => valid_attributes}, valid_session
        }.to change(LaborCart, :count).by(1)
      end

      it "assigns a newly created labor_cart as @labor_cart" do
        post :create, {:labor_cart => valid_attributes}, valid_session
        assigns(:labor_cart).should be_a(LaborCart)
        assigns(:labor_cart).should be_persisted
      end

      it "redirects to the created labor_cart" do
        post :create, {:labor_cart => valid_attributes}, valid_session
        response.should redirect_to(LaborCart.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved labor_cart as @labor_cart" do
        # Trigger the behavior that occurs when invalid params are submitted
        LaborCart.any_instance.stub(:save).and_return(false)
        post :create, {:labor_cart => {  }}, valid_session
        assigns(:labor_cart).should be_a_new(LaborCart)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        LaborCart.any_instance.stub(:save).and_return(false)
        post :create, {:labor_cart => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested labor_cart" do
        labor_cart = LaborCart.create! valid_attributes
        # Assuming there are no other labor_carts in the database, this
        # specifies that the LaborCart created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        LaborCart.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => labor_cart.to_param, :labor_cart => { "these" => "params" }}, valid_session
      end

      it "assigns the requested labor_cart as @labor_cart" do
        labor_cart = LaborCart.create! valid_attributes
        put :update, {:id => labor_cart.to_param, :labor_cart => valid_attributes}, valid_session
        assigns(:labor_cart).should eq(labor_cart)
      end

      it "redirects to the labor_cart" do
        labor_cart = LaborCart.create! valid_attributes
        put :update, {:id => labor_cart.to_param, :labor_cart => valid_attributes}, valid_session
        response.should redirect_to(labor_cart)
      end
    end

    describe "with invalid params" do
      it "assigns the labor_cart as @labor_cart" do
        labor_cart = LaborCart.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LaborCart.any_instance.stub(:save).and_return(false)
        put :update, {:id => labor_cart.to_param, :labor_cart => {  }}, valid_session
        assigns(:labor_cart).should eq(labor_cart)
      end

      it "re-renders the 'edit' template" do
        labor_cart = LaborCart.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LaborCart.any_instance.stub(:save).and_return(false)
        put :update, {:id => labor_cart.to_param, :labor_cart => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested labor_cart" do
      labor_cart = LaborCart.create! valid_attributes
      expect {
        delete :destroy, {:id => labor_cart.to_param}, valid_session
      }.to change(LaborCart, :count).by(-1)
    end

    it "redirects to the labor_carts list" do
      labor_cart = LaborCart.create! valid_attributes
      delete :destroy, {:id => labor_cart.to_param}, valid_session
      response.should redirect_to(labor_carts_url)
    end
  end

end
